# This is a basic workflow to help you get started with Actions

name: BiberNotification

on:
  schedule:
    - cron:  "*/10 * * * *"

  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Load requirements
        run: pip install -r requirements.txt
      - name: Run script
        run: python bibernotification.py
