# This is a basic workflow to help you get started with Actions

name: BiberNotification

on:
  schedule:
    - cron:  "*/10 * * * *"

  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!
